/*
  Warnings:

  - Made the column `qr_code` on table `InventoryItem` required. This step will fail if there are existing NULL values in that column.

*/
-- First, update existing NULL qr_codes with generated values
UPDATE "InventoryItem"
SET "qr_code" = CONCAT(
  SUBSTRING('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ' FROM (CEIL(RANDOM() * 36)::INTEGER) FOR 1),
  SUBSTRING('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ' FROM (CEIL(RANDOM() * 36)::INTEGER) FOR 1),
  SUBSTRING('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ' FROM (CEIL(RANDOM() * 36)::INTEGER) FOR 1),
  SUBSTRING('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ' FROM (CEIL(RANDOM() * 36)::INTEGER) FOR 1),
  SUBSTRING('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ' FROM (CEIL(RANDOM() * 36)::INTEGER) FOR 1),
  SUBSTRING('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ' FROM (CEIL(RANDOM() * 36)::INTEGER) FOR 1),
  SUBSTRING('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ' FROM (CEIL(RANDOM() * 36)::INTEGER) FOR 1),
  SUBSTRING('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ' FROM (CEIL(RANDOM() * 36)::INTEGER) FOR 1)
)
WHERE "qr_code" IS NULL;

-- Now make the column required
ALTER TABLE "InventoryItem" ALTER COLUMN "qr_code" SET NOT NULL;
